import { StyleSheet } from "@react-pdf/renderer";
import type { KpiCardVariant } from "@/components/cards/AnalyticsCard";

export const PDF_COLORS = {
  slate50: "#f8fafc",
  slate100: "#f1f5f9",
  slate200: "#e2e8f0",
  slate500: "#64748b",
  slate600: "#475569",
  slate900: "#0f172a",
  white: "#ffffff",
  defenceGreen: "#138808",
  positive: "#22c55e",
  negative: "#ef4444",
  neutral: "#eab308",
  print: "#1e40af",
  online: "#059669",
  twitter: "#0ea5e9",
  youtube: "#dc2626",
} as const;

export const KPI_VARIANT_STYLES: Record<
  KpiCardVariant,
  { border: string; value: string; accent: string; badgeBg: string; badgeText: string }
> = {
  default: {
    border: PDF_COLORS.slate200,
    value: PDF_COLORS.slate900,
    accent: PDF_COLORS.slate900,
    badgeBg: PDF_COLORS.slate100,
    badgeText: PDF_COLORS.slate600,
  },
  positive: {
    border: "#a7f3d0",
    value: "#047857",
    accent: PDF_COLORS.positive,
    badgeBg: "#d1fae5",
    badgeText: "#047857",
  },
  negative: {
    border: "#fecaca",
    value: "#b91c1c",
    accent: PDF_COLORS.negative,
    badgeBg: "#fee2e2",
    badgeText: "#b91c1c",
  },
  neutral: {
    border: "#fde68a",
    value: "#b45309",
    accent: PDF_COLORS.neutral,
    badgeBg: "#fef3c7",
    badgeText: "#b45309",
  },
  print: {
    border: "#bfdbfe",
    value: "#1d4ed8",
    accent: PDF_COLORS.print,
    badgeBg: "#dbeafe",
    badgeText: "#1d4ed8",
  },
  online: {
    border: "#99f6e4",
    value: "#0f766e",
    accent: PDF_COLORS.online,
    badgeBg: "#ccfbf1",
    badgeText: "#0f766e",
  },
  twitter: {
    border: "#bae6fd",
    value: "#0369a1",
    accent: PDF_COLORS.twitter,
    badgeBg: "#e0f2fe",
    badgeText: "#0369a1",
  },
  youtube: {
    border: "#fecdd3",
    value: "#be123c",
    accent: PDF_COLORS.youtube,
    badgeBg: "#ffe4e6",
    badgeText: "#be123c",
  },
};

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 48,
    paddingHorizontal: 32,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: PDF_COLORS.slate900,
    backgroundColor: PDF_COLORS.white,
  },
  pageHeader: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.slate200,
    paddingBottom: 10,
  },
  pageTitle: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.slate900,
  },
  pageSubtitle: {
    marginTop: 4,
    fontSize: 9,
    color: PDF_COLORS.slate500,
  },
  sectionGap: {
    marginBottom: 14,
  },
  row: {
    flexDirection: "row",
    gap: 8,
  },
  kpiGrid4: {
    flexDirection: "row",
    gap: 8,
  },
  kpiGrid8: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  kpiCard: {
    flex: 1,
    minWidth: 110,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: PDF_COLORS.white,
    position: "relative",
  },
  kpiAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  kpiTitle: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.slate500,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 6,
    paddingLeft: 4,
  },
  kpiValue: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    paddingLeft: 4,
  },
  kpiBadge: {
    marginTop: 4,
    marginLeft: 4,
    alignSelf: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
  },
  chartBox: {
    borderWidth: 1,
    borderColor: PDF_COLORS.slate200,
    borderRadius: 8,
    padding: 12,
    backgroundColor: PDF_COLORS.white,
    minHeight: 120,
  },
  chartTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.slate900,
    marginBottom: 2,
  },
  chartSubtitle: {
    fontSize: 8,
    color: PDF_COLORS.slate500,
    marginBottom: 10,
  },
  tableSectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.slate900,
    marginBottom: 8,
    marginTop: 4,
  },
  table: {
    borderWidth: 1,
    borderColor: PDF_COLORS.slate200,
    borderRadius: 8,
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: PDF_COLORS.slate100,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.slate200,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  tableRowAlt: {
    backgroundColor: "#fafafa",
  },
  tableHeaderCell: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.slate600,
    textTransform: "uppercase",
  },
  tableHeaderCellCenter: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.slate600,
    textTransform: "uppercase",
    textAlign: "center",
  },
  tableCell: {
    paddingVertical: 5,
    paddingHorizontal: 4,
    fontSize: 7,
    color: PDF_COLORS.slate600,
  },
  tableCellCenter: {
    paddingVertical: 5,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  tableLink: {
    fontSize: 7,
    color: PDF_COLORS.defenceGreen,
    textDecoration: "underline",
  },
  sentimentBadge: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 8,
    fontSize: 7,
    color: PDF_COLORS.white,
    textTransform: "capitalize",
    textAlign: "center",
    alignSelf: "center",
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 32,
    right: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.slate200,
    paddingTop: 8,
    fontSize: 8,
    color: PDF_COLORS.slate500,
  },
  legendRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
    marginTop: 8,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  legendSwatch: {
    width: 10,
    height: 10,
    borderRadius: 2,
  },
  legendText: {
    fontSize: 8,
    color: PDF_COLORS.slate600,
  },
});
